name: Build Libraries x64

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Without the proper visual studio development environment, devenv and/or msbuild will not be found.
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      # Run the actual build script
      - name: Build libraries
        run: |
          .\build.ps1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload the build artifacts
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fnalibs-win-x64
          path: artifacts/